version: '3.8'
services:
  postgres:
    image: postgres:15-apine
    container_name: chatpeople-postgres
    restart: always
    environment:
      - POSTGRES_DB=chatpeople
      - POSTGRES_USER=xtremedev
      - POSTGRES_PASSWORD=Yan%40jan2019
    volumes:
      - chatpeople:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
